version: '3.8'

services:

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "8080:8000"  # Maps port 8080 on the host to port 8000 in the container

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
